### ISSUE TITLE
Wiki changes

### ISSUE THREAD

**Issue by ghost** [mozilla/mozilla.github.io#14]
FYI: The following changes were made to this repository's wiki:

- defacing spam has been removed

- Restricting write access to contributors is strongly encouraged.  Please [make that change](https://github.com/mozilla/mozilla.github.io/settings)  ([documentation](https://help.github.com/articles/changing-access-permissions-for-wikis/)).

These were made as the result of a recent automated defacement of publically writeable wikis.

**Comment by imSanko** [comment]
I wanna work on to this project can you assign it to me.

**Comment by ghost** [comment]
> I wanna work on to this project can you assign it to me.

Sorry - this was an "informational issue", and should have been closed long ago.

Thanks for your interest in helping us! We've got a partial list of [starting places](https://wiki.mozilla.org/GitHub#Can_I_be_a_Member_of_the_Mozilla_Organization.3F) that should get you to newer stuff.
