### ISSUE TITLE
404 Link

### ISSUE THREAD

**Issue by trashbirdecology** [mozilla/mozilla.github.io#21]
Link, http://smartbear.com/smartbear/media/pdfs/wp-cc-11-best-practices-of-peer-code-review.pdf, provided in phrase "this study" at [this website](https://mozillascience.github.io/codeReview/contrib.html) is 404
> Maximum submission length of 400 lines. It's impossible to review thousands of lines of code in a sitting; **this study** recommends no more than 400 lines at once. Going beyond this reduces the amount of bugs we can successfully detect, while making the amount of time needed for code review blow up. If more changes than this are required, they should almost certainly be in separate contributions.

**Comment by tanmaythaakur** [comment]
Hello, I would like you to assign this to me as I have found a link that is working. I would like to add it. Thank you.
