### ISSUE TITLE
Enforce HTTPS for mozilla.github.io

### ISSUE THREAD

**Issue by konklone** [mozilla/mozilla.github.io#8]
GitHub now lets you enforce HTTPS for `*.github.io` domains:

https://github.com/blog/2186-https-for-github-pages

The site already works over HTTPS without errors: https://mozilla.github.io So this should be a trivial fix.

I recommend going through any other repos that use the mozilla.github.io domain (if there are any) to flip the switch there too.

![support page](https://help.github.com/assets/images/help/pages/enforce-https-checkbox.png)

**Comment by jgmize** [comment]
I verified this setting was enabled previously; closing old issue.
